INSERT INTO pessoa (tipo, nome, email) VALUES
('FISICA', 'Luana Cordeiro', 'luana.cordeiro@gmail.com'),
('FISICA', 'Matheus Andrade', 'matheus.andrade@hotmail.com'),
('FISICA', 'Fernanda Baptista', 'fer.baptista@yahoo.com'),
('FISICA', 'Gabriel Monteiro', 'gabriel.monteiro@gmail.com'),
('FISICA', 'Daniela Azevedo', 'daniela.azevedo@outlook.com'),
('FISICA', 'Rafael Moura', 'rafa.moura@gmail.com'),
('FISICA', 'Carolina Peixoto', 'carol.peixoto@gmail.com'),
('FISICA', 'Hélio Farias', 'helio.farias@yahoo.com'),
('FISICA', 'Clarissa Moretti', 'clarissa.moretti@gmail.com'),
('FISICA', 'Thiago Cordeiro', 'thiago.cordeiro@hotmail.com'),
('FISICA', 'Juliana Gonçalves', 'juliana.goncalves@gmail.com'),
('FISICA', 'Bruno Soares', 'bruno.soares@gmail.com'),
('FISICA', 'Paula Menezes', 'paula.menezes@hotmail.com'),
('FISICA', 'Felipe Barreto', 'felipe.barreto@gmail.com'),
('FISICA', 'Sabrina Villar', 'sabrina.villar@gmail.com'),
('FISICA', 'Leonardo Bernardes', 'leo.bernardes@hotmail.com'),
('FISICA', 'Camila Furtado', 'camila.furtado@gmail.com'),
('FISICA', 'Rogério Siqueira', 'rogerio.siqueira@gmail.com'),
('FISICA', 'Tatiana Ribeiro', 'tatiana.ribeiro@yahoo.com'),
('FISICA', 'Vinícius Costa', 'vinicius.costa@gmail.com'),
('FISICA', 'Aline Fernandes', 'aline.fernandes@hotmail.com'),
('FISICA', 'Marcelo Torres', 'marcelo.torres@gmail.com'),
('FISICA', 'Eduarda Martins', 'eduarda.martins@gmail.com'),
('FISICA', 'João Pedro Silveira', 'joaopedro.silveira@gmail.com'),
('FISICA', 'Renata Albuquerque', 'renata.albuquerque@hotmail.com'),
('FISICA', 'Gustavo Nogueira', 'gustavo.nogueira@gmail.com'),
('FISICA', 'Isabela Vasques', 'isabela.vasques@gmail.com'),
('FISICA', 'Alexandre Motta', 'alex.motta@yahoo.com'),
('FISICA', 'Bruna Castro', 'bruna.castro@gmail.com'),
('FISICA', 'Caio Amaral', 'caio.amaral@gmail.com'),
('FISICA', 'Letícia Vieira', 'leticia.vieira@hotmail.com'),
('FISICA', 'Pedro Pacheco', 'pedro.pacheco@gmail.com'),
('FISICA', 'Lorena Dias', 'lorena.dias@gmail.com'),
('FISICA', 'Fábio Rezende', 'fabio.rezende@yahoo.com'),
('FISICA', 'Patrícia Dantas', 'patricia.dantas@gmail.com'),
('FISICA', 'Henrique Moreira', 'henrique.moreira@gmail.com'),
('FISICA', 'Joana Barros', 'joana.barros@gmail.com'),
('FISICA', 'Eduardo Carvalho', 'eduardo.carvalho@hotmail.com'),
('FISICA', 'Yasmin Rocha', 'yasmin.rocha@gmail.com'),
('FISICA', 'Cláudio Nunes', 'claudio.nunes@yahoo.com'),
('FISICA', 'Carla Bastos', 'carla.bastos@gmail.com'),
('FISICA', 'Marcos Lima', 'marcos.lima@gmail.com'),
('FISICA', 'Viviane Corrêa', 'viviane.correa@yahoo.com'),
('FISICA', 'Rafael Tavares', 'rafa.tavares@gmail.com'),
('FISICA', 'Jéssica Luz', 'jessica.luz@gmail.com'),
('FISICA', 'Wagner Ribeiro', 'wagner.ribeiro@gmail.com'),
('FISICA', 'Helena Duarte', 'helena.duarte@hotmail.com'),
('FISICA', 'Lucas Ferreira', 'lucas.ferreira@gmail.com'),
('FISICA', 'Mariana Cunha', 'mariana.cunha@gmail.com'),
('FISICA', 'Otávio Mendes', 'otavio.mendes@gmail.com'),
('FISICA', 'Nathalia Peixoto', 'nathalia.peixoto@yahoo.com'),
('FISICA', 'Cristiano Sales', 'cristiano.sales@gmail.com'),
('FISICA', 'Beatriz Mourão', 'bia.mourao@gmail.com'),
('FISICA', 'Samuel Braga', 'samuel.braga@hotmail.com'),
('FISICA', 'Gabriela Teixeira', 'gabriela.teixeira@gmail.com'),
('FISICA', 'Ricardo Almeida', 'ricardo.almeida@gmail.com'),
('FISICA', 'Lívia Campos', 'livia.campos@yahoo.com'),
('FISICA', 'Caio Henrique', 'caio.henrique@gmail.com'),
('FISICA', 'Melissa Cardoso', 'melissa.cardoso@gmail.com'),
('FISICA', 'Pedro Henrique', 'pedro.henrique@hotmail.com'),
('FISICA', 'Juliano Rocha', 'juliano.rocha@gmail.com'),
('FISICA', 'Sara Ventura', 'sara.ventura@gmail.com'),
('FISICA', 'Fernando Silveira', 'fernando.silveira@yahoo.com'),
('FISICA', 'Ariane Matos', 'ariane.matos@gmail.com'),
('FISICA', 'Matheus Pinheiro', 'matheus.pinheiro@gmail.com'),
('FISICA', 'Amanda Vieira', 'amanda.vieira@hotmail.com'),
('FISICA', 'Rafael Cunha', 'rafael.cunha@gmail.com'),
('FISICA', 'Clara Mendonça', 'clara.mendonca@gmail.com'),
('FISICA', 'Douglas Batista', 'douglas.batista@gmail.com'),
('FISICA', 'Monique Cardozo', 'monique.cardozo@gmail.com'),
('FISICA', 'Henrique Lemos', 'henrique.lemos@hotmail.com'),
('FISICA', 'Sofia Ribeiro', 'sofia.ribeiro@gmail.com'),
('FISICA', 'Guilherme França', 'g.franca@gmail.com'),
('FISICA', 'Carolina Souza', 'carolina.souza@hotmail.com'),
('FISICA', 'Lucas Antunes', 'lucas.antunes@gmail.com'),
('FISICA', 'Bianca Ramos', 'bianca.ramos@gmail.com'),
('FISICA', 'Fabrício Carvalho', 'fabricio.carvalho@gmail.com'),
('FISICA', 'Tatiane Maia', 'tatiane.maia@hotmail.com'),
('FISICA', 'Roberto Valentim', 'roberto.valentim@gmail.com'),
('FISICA', 'Elisa Torres', 'elisa.torres@gmail.com'),
('FISICA', 'Marcelo Furtado', 'marcelo.furtado@gmail.com'),
('FISICA', 'Carina Lopes', 'carina.lopes@gmail.com'),
('FISICA', 'Thiago Ramos', 't.ramos@hotmail.com'),
('FISICA', 'Júlia Fernandes', 'julia.fernandes@gmail.com'),
('FISICA', 'Rogério Macedo', 'rogerio.macedo@gmail.com'),
('FISICA', 'Luiza Santos', 'luiza.santos@hotmail.com'),
('FISICA', 'Cristian Vieira', 'cristian.vieira@gmail.com'),
('FISICA', 'Mariana Correa', 'mariana.correa@gmail.com'),
('FISICA', 'Renato Oliveira', 'renato.oliveira@gmail.com'),
('FISICA', 'Juliana Nascimento', 'juliana.nasci@gmail.com'),
('FISICA', 'Bruno Vieira', 'bruno.vieira@gmail.com'),
('FISICA', 'Daniel Castro', 'daniel.castro@yahoo.com'),
('FISICA', 'Patrícia Rezende', 'paty.rezende@gmail.com'),
('FISICA', 'Hugo Lima', 'hugo.lima@hotmail.com'),
('FISICA', 'Natália Diniz', 'natalia.diniz@gmail.com'),
('FISICA', 'Alan Costa', 'alan.costa@gmail.com'),
('FISICA', 'Sabrina Oliveira', 'sabrina.oliveira@hotmail.com'),
('FISICA', 'Arthur Reis', 'arthur.reis@gmail.com'),
('FISICA', 'Leila Moura', 'leila.moura@gmail.com'),
('FISICA', 'Vinícius Duarte', 'vinicius.duarte@hotmail.com'),

----------------------------------------
-- 100 PESSOAS JURÍDICAS
----------------------------------------

('JURIDICA','AgroTerra Comercial Ltda','contato@agroterra.com'),
('JURIDICA','BioNutri Indústrias Agrícolas','suporte@bionutri.com'),
('JURIDICA','Fazenda São Gabriel S/A','administrativo@fazsga.com'),
('JURIDICA','NutriBov Agropecuária','vendas@nutribov.com.br'),
('JURIDICA','Agro Vale do Sol Ltda','contato@valedosol.com'),
('JURIDICA','Campo Verde Exportações','export@campoverde.com'),
('JURIDICA','Granja Modelo Alimentos','suporte@granjamodelo.com'),
('JURIDICA','Master Rações Ltda','vendas@masterracoes.com'),
('JURIDICA','AgriTech Brasil','contato@agritechbr.com'),
('JURIDICA','AgroNorte Suprimentos','atendimento@agronorte.com'),
('JURIDICA','Rações Brasil S/A','comercial@racoesbrasil.com'),
('JURIDICA','Biogran AgroNutrição','biogran@nutri.com'),
('JURIDICA','AgroLopes Alimentos','agrolopes@gmail.com'),
('JURIDICA','Fazenda Nova Esperança','contato@novaesperanca.com'),
('JURIDICA','AlfaNutri Produtos Rurais','alfa@nutri.com'),
('JURIDICA','CooperBov Cooperativa','adm@cooperbov.com'),
('JURIDICA','Campo Forte Suprimentos','info@campoforte.com'),
('JURIDICA','RuralMix Distribuidora','ruralmix@distribuidora.com'),
('JURIDICA','BioCampo Nutrição Animal','biocampo@nutri.com'),
('JURIDICA','AgroPrime Trading','trading@agroprime.com'),
('JURIDICA','Granja Vitória Comércio Rural','contato@granvitoria.com'),
('JURIDICA','NutriPlus Agro','nutriplus@agro.com'),
('JURIDICA','HortiBov Alimentos','hortibov@alimentos.com'),
('JURIDICA','SuperCampo Produtos Agro','supercampo@agro.com'),
('JURIDICA','ValleRações Indústria','valleracoes@ind.com'),
('JURIDICA','AgroSilva Fornecimentos','suporte@agrosilva.com'),
('JURIDICA','Rural Pro Distribuidora','atendimento@ruralpro.com'),
('JURIDICA','BioAgro Brasil','contato@bioagro.com'),
('JURIDICA','MasterBov Suprimentos','masterbov@forn.com'),
('JURIDICA','Fazenda Alto Céu','altoceu@fazenda.com'),
('JURIDICA','VerdeCampo Agropecuária','contato@verdecampo.com'),
('JURIDICA','Nutrivale Serviços Rurais','nutrivale@rural.com'),
('JURIDICA','Granja Santa Clara','santaclara@granja.com'),
('JURIDICA','PastoForte Nutrição Animal','pastoforte@nutri.com'),
('JURIDICA','AgroSim Ltda','agrosim@contato.com'),
('JURIDICA','RuralMax Produtos','ruralmax@produtos.com'),
('JURIDICA','AgroLeste Fornecedores','agroleste@forn.com'),
('JURIDICA','NutriBois Agro','nutribois@agro.com'),
('JURIDICA','Campo Alto Alimentos','campoalto@alimentos.com'),
('JURIDICA','BoviNutri Importações','import@bovinutri.com'),
('JURIDICA','AgroCana Comércio','agrocana@comercial.com'),
('JURIDICA','HortiVale Agricola','hortivale@agro.com'),
('JURIDICA','MegaRações S/A','mega@racoes.com'),
('JURIDICA','SuperBov Nutrição','superbov@nutri.com'),
('JURIDICA','BrasilAgro Produtos','brasilagro@vendas.com'),
('JURIDICA','PastoSul Trading','pastosul@trading.com'),
('JURIDICA','Central Bovina','central@bovina.com'),
('JURIDICA','AgroForte Ltda','agroforte@forn.com'),
('JURIDICA','Indústria RuralMix','ind@ruralmix.com'),
('JURIDICA','BovTec Soluções Rurais','bovtec@solutions.com'),
('JURIDICA','FarmaNutri AgroVet','farmanutri@vet.com'),
('JURIDICA','AgroVital Produtos','agrovital@produtos.com'),
('JURIDICA','Biomix Nutrição','biomix@nutri.com'),
('JURIDICA','Granja Paulista','contato@granjapaulista.com'),
('JURIDICA','Vitale Agro','vitale@agro.com'),
('JURIDICA','SupraRural Suprimentos','suprarural@sup.com'),
('JURIDICA','CampoReal Export','camporeal@export.com'),
('JURIDICA','AgroSerrano','contato@agroserrano.com'),
('JURIDICA','GranBov Fornecedores','granbov@forn.com'),
('JURIDICA','GreenField Agro','contato@greenfield.com'),
('JURIDICA','NutriCamp Produtos Rurais','nutricamp@produtos.com'),
('JURIDICA','SuperAgro Brasil','info@superagro.com'),
('JURIDICA','HiperRações Distribuidora','hiper@racoes.com'),
('JURIDICA','GranNutri Agropecuária','grannutri@agro.com'),
('JURIDICA','Vale Norte Alimentos','valenorte@alimentos.com'),
('JURIDICA','Agro+ Nutrição','agroplus@nutri.com'),
('JURIDICA','NutriRural Comércio','nutrirural@com.com'),
('JURIDICA','Rações Vitória Ltda','vitoria@racoes.com'),
('JURIDICA','Tecnobov Soluções','tecnobov@solucoes.com'),
('JURIDICA','Brasil Campo Agro','brasilcampo@agro.com'),
('JURIDICA','SuperAlfa Produtos Rurais','superalfa@com.com'),
('JURIDICA','AgroPampa','agropampa@agro.com'),
('JURIDICA','NutriSul Rações','nutrisul@racoes.com'),
('JURIDICA','GreenBov Export','export@greenbov.com'),
('JURIDICA','Fazenda Bela Vista','belavista@fazenda.com'),
('JURIDICA','Nutri-Forte Alimentos','nutriforte@alimentos.com'),
('JURIDICA','Granja Horizonte','horizonte@granja.com'),
('JURIDICA','Campo e Vida Suprimentos','campo.vida@suprimentos.com'),
('JURIDICA','BioAlfa Agro','bioalfa@agro.com'),
('JURIDICA','RuralPartners Ltda','partners@rural.com'),
('JURIDICA','MegaCampo S/A','mega@campo.com'),
('JURIDICA','EcoNutri Produtos Rurais','econutri@agro.com'),
('JURIDICA','Fazenda Rio Azul','rioazul@fazenda.com'),
('JURIDICA','BovinoTech Indústria','bovinotech@ind.com'),
('JURIDICA','AgroServ Distribuidora','agroserv@dist.com'),
('JURIDICA','PetroAgro Suprimentos','petroagro@suprimentos.com'),
('JURIDICA','AgroBrasil Fornecimentos','agrobrasil@br.com'),
('JURIDICA','BioRações Brasil','bioracoes@br.com'),
('JURIDICA','GranHorti Alimentos','granhorti@alimentos.com'),
('JURIDICA','NutriFazenda Vet','nutrifaz@vet.com'),
('JURIDICA','NutriBoi Importações','nutriboi@import.com'),
('JURIDICA','AgroVale Brasil','agrovale@brasil.com'),
('JURIDICA','Campo Global Exportações','global@campo.com'),
('JURIDICA','VetPlus AgroVet','vetplus@agrovet.com'),
('JURIDICA','FarmaCampo Nutrição','farmacampo@nutri.com'),
('JURIDICA','SuperMix Agro','supermix@agro.com'),
('JURIDICA','AgroFazenda Prime','prime@agrofazenda.com'),
('JURIDICA','MegaBov Comércio Rural','megabov@cr.com'),
('JURIDICA','BioRural Soluções','biorural@solutions.com'),
('JURIDICA','Granja Central Paulista','central@granjapaulista.com');